// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: memory_manager.proto

#include "memory_manager.pb.h"
#include "memory_manager.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace memory_manager {

static const char* MemoryService_method_names[] = {
  "/memory_manager.MemoryService/Create",
  "/memory_manager.MemoryService/Set",
  "/memory_manager.MemoryService/Get",
  "/memory_manager.MemoryService/IncreaseRefCount",
  "/memory_manager.MemoryService/DecreaseRefCount",
};

std::unique_ptr< MemoryService::Stub> MemoryService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MemoryService::Stub> stub(new MemoryService::Stub(channel, options));
  return stub;
}

MemoryService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Create_(MemoryService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Set_(MemoryService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Get_(MemoryService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_IncreaseRefCount_(MemoryService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DecreaseRefCount_(MemoryService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MemoryService::Stub::Create(::grpc::ClientContext* context, const ::memory_manager::CreateRequest& request, ::memory_manager::CreateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::memory_manager::CreateRequest, ::memory_manager::CreateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Create_, context, request, response);
}

void MemoryService::Stub::async::Create(::grpc::ClientContext* context, const ::memory_manager::CreateRequest* request, ::memory_manager::CreateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::memory_manager::CreateRequest, ::memory_manager::CreateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Create_, context, request, response, std::move(f));
}

void MemoryService::Stub::async::Create(::grpc::ClientContext* context, const ::memory_manager::CreateRequest* request, ::memory_manager::CreateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Create_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::CreateResponse>* MemoryService::Stub::PrepareAsyncCreateRaw(::grpc::ClientContext* context, const ::memory_manager::CreateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::memory_manager::CreateResponse, ::memory_manager::CreateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Create_, context, request);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::CreateResponse>* MemoryService::Stub::AsyncCreateRaw(::grpc::ClientContext* context, const ::memory_manager::CreateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MemoryService::Stub::Set(::grpc::ClientContext* context, const ::memory_manager::SetRequest& request, ::memory_manager::SetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::memory_manager::SetRequest, ::memory_manager::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Set_, context, request, response);
}

void MemoryService::Stub::async::Set(::grpc::ClientContext* context, const ::memory_manager::SetRequest* request, ::memory_manager::SetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::memory_manager::SetRequest, ::memory_manager::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, std::move(f));
}

void MemoryService::Stub::async::Set(::grpc::ClientContext* context, const ::memory_manager::SetRequest* request, ::memory_manager::SetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::SetResponse>* MemoryService::Stub::PrepareAsyncSetRaw(::grpc::ClientContext* context, const ::memory_manager::SetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::memory_manager::SetResponse, ::memory_manager::SetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Set_, context, request);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::SetResponse>* MemoryService::Stub::AsyncSetRaw(::grpc::ClientContext* context, const ::memory_manager::SetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MemoryService::Stub::Get(::grpc::ClientContext* context, const ::memory_manager::GetRequest& request, ::memory_manager::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::memory_manager::GetRequest, ::memory_manager::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Get_, context, request, response);
}

void MemoryService::Stub::async::Get(::grpc::ClientContext* context, const ::memory_manager::GetRequest* request, ::memory_manager::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::memory_manager::GetRequest, ::memory_manager::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void MemoryService::Stub::async::Get(::grpc::ClientContext* context, const ::memory_manager::GetRequest* request, ::memory_manager::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::GetResponse>* MemoryService::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::memory_manager::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::memory_manager::GetResponse, ::memory_manager::GetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Get_, context, request);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::GetResponse>* MemoryService::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::memory_manager::GetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MemoryService::Stub::IncreaseRefCount(::grpc::ClientContext* context, const ::memory_manager::RefCountRequest& request, ::memory_manager::RefCountResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::memory_manager::RefCountRequest, ::memory_manager::RefCountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_IncreaseRefCount_, context, request, response);
}

void MemoryService::Stub::async::IncreaseRefCount(::grpc::ClientContext* context, const ::memory_manager::RefCountRequest* request, ::memory_manager::RefCountResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::memory_manager::RefCountRequest, ::memory_manager::RefCountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_IncreaseRefCount_, context, request, response, std::move(f));
}

void MemoryService::Stub::async::IncreaseRefCount(::grpc::ClientContext* context, const ::memory_manager::RefCountRequest* request, ::memory_manager::RefCountResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_IncreaseRefCount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::RefCountResponse>* MemoryService::Stub::PrepareAsyncIncreaseRefCountRaw(::grpc::ClientContext* context, const ::memory_manager::RefCountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::memory_manager::RefCountResponse, ::memory_manager::RefCountRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_IncreaseRefCount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::RefCountResponse>* MemoryService::Stub::AsyncIncreaseRefCountRaw(::grpc::ClientContext* context, const ::memory_manager::RefCountRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncIncreaseRefCountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MemoryService::Stub::DecreaseRefCount(::grpc::ClientContext* context, const ::memory_manager::RefCountRequest& request, ::memory_manager::RefCountResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::memory_manager::RefCountRequest, ::memory_manager::RefCountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DecreaseRefCount_, context, request, response);
}

void MemoryService::Stub::async::DecreaseRefCount(::grpc::ClientContext* context, const ::memory_manager::RefCountRequest* request, ::memory_manager::RefCountResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::memory_manager::RefCountRequest, ::memory_manager::RefCountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DecreaseRefCount_, context, request, response, std::move(f));
}

void MemoryService::Stub::async::DecreaseRefCount(::grpc::ClientContext* context, const ::memory_manager::RefCountRequest* request, ::memory_manager::RefCountResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DecreaseRefCount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::RefCountResponse>* MemoryService::Stub::PrepareAsyncDecreaseRefCountRaw(::grpc::ClientContext* context, const ::memory_manager::RefCountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::memory_manager::RefCountResponse, ::memory_manager::RefCountRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DecreaseRefCount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::memory_manager::RefCountResponse>* MemoryService::Stub::AsyncDecreaseRefCountRaw(::grpc::ClientContext* context, const ::memory_manager::RefCountRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDecreaseRefCountRaw(context, request, cq);
  result->StartCall();
  return result;
}

MemoryService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryService::Service, ::memory_manager::CreateRequest, ::memory_manager::CreateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MemoryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::memory_manager::CreateRequest* req,
             ::memory_manager::CreateResponse* resp) {
               return service->Create(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryService::Service, ::memory_manager::SetRequest, ::memory_manager::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MemoryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::memory_manager::SetRequest* req,
             ::memory_manager::SetResponse* resp) {
               return service->Set(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryService::Service, ::memory_manager::GetRequest, ::memory_manager::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MemoryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::memory_manager::GetRequest* req,
             ::memory_manager::GetResponse* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryService::Service, ::memory_manager::RefCountRequest, ::memory_manager::RefCountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MemoryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::memory_manager::RefCountRequest* req,
             ::memory_manager::RefCountResponse* resp) {
               return service->IncreaseRefCount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryService::Service, ::memory_manager::RefCountRequest, ::memory_manager::RefCountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MemoryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::memory_manager::RefCountRequest* req,
             ::memory_manager::RefCountResponse* resp) {
               return service->DecreaseRefCount(ctx, req, resp);
             }, this)));
}

MemoryService::Service::~Service() {
}

::grpc::Status MemoryService::Service::Create(::grpc::ServerContext* context, const ::memory_manager::CreateRequest* request, ::memory_manager::CreateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MemoryService::Service::Set(::grpc::ServerContext* context, const ::memory_manager::SetRequest* request, ::memory_manager::SetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MemoryService::Service::Get(::grpc::ServerContext* context, const ::memory_manager::GetRequest* request, ::memory_manager::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MemoryService::Service::IncreaseRefCount(::grpc::ServerContext* context, const ::memory_manager::RefCountRequest* request, ::memory_manager::RefCountResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MemoryService::Service::DecreaseRefCount(::grpc::ServerContext* context, const ::memory_manager::RefCountRequest* request, ::memory_manager::RefCountResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace memory_manager

